import argparse
import os
import sys
import os.path as opath

import cv2
import numpy as np
from tqdm import tqdm

__dir__ = os.path.dirname(os.path.abspath(__file__))
sys.path.append(os.path.abspath(os.path.join(__dir__, '../../../')))
from paddleseg.utils import get_sys_env, logger, get_image_list

from infer import Predictor
import humanseg_infer as hseg


def parse_args():
    parser = argparse.ArgumentParser(
        description='PP-HumanSeg inference for video')
    parser.add_argument(
        "--config",
        help="The config file of the inference model.",
        type=str,
        required=True)
    parser.add_argument(
        '--img_dir', help='The image that to be predicted.', type=str)
    parser.add_argument(
        '--label_dir', help='dir of labels related to the images.', type=str)
    parser.add_argument(
        '--bg_img_dir',
        help='Background image path for replacing. If not specified, a white background is used',
        type=str)
    parser.add_argument(
        '--save_dir',
        help='The directory for saving the inference results',
        type=str,
        default='./output')

    parser.add_argument(
        '--vertical_screen',
        help='The input image is generated by vertical screen, i.e. height is bigger than width.'
        'For the input image, we assume the width is bigger than the height by default.',
        action='store_true')
    parser.add_argument(
        '--use_post_process', help='Use post process.', action='store_true')
    parser.add_argument(
        '--use_optic_flow', help='Use optical flow.', action='store_true')
    parser.add_argument(
        '--test_speed',
        help='Whether to test inference speed',
        action='store_true')

    return parser.parse_args()


def seg_image(args):
    assert os.path.exists(args.img_path), \
        "The --img_path is not existed: {}.".format(args.img_path)

    logger.info("Input: image")
    logger.info("Create predictor...")
    predictor = Predictor(args)

    logger.info("Start predicting...")
    img = cv2.imread(args.img_path, cv2.IMREAD_COLOR)
    bg_img = cv2.imread(args.bg_img_path, cv2.IMREAD_COLOR)
    # out_img = predictor.run(img, bg_img)
    # cv2.imwrite(args.save_dir, out_img)

    predictor2 = hseg.Predictor(args)
    mask = predictor2.predict_img(img)
    merge_img = hseg.merge_img(img, mask, bg_img)
    cv2.imwrite('new2.jpg', merge_img)

def get_model(args):
    logger.info("Create predictor...")
    predictor = hseg.Predictor(args)
    return predictor

def read_labels(label_file: str):
    def get_line_label(line):
        parts = line.strip().split(' ')
        return [int(parts[0])] + list(map(float, parts[1:]))
    with open(label_file, 'r') as fp:
        lines = fp.readlines()
    return [get_line_label(line) for line in lines]

def save_labels(label_file: str, boxes):
    with open(label_file, 'w') as fp:
        for box in boxes:
            l = ' '.join([str(x) for x in box])
            fp.write(f'{l}\n')

if __name__ == "__main__":
    args = parse_args()
    print(args)

    env_info = get_sys_env()
    args.use_gpu = True if env_info['Paddle compiled with cuda'] \
        and env_info['GPUs used'] else False

    save_dir = args.save_dir
    save_dir = save_dir if os.path.isdir(save_dir) else os.path.dirname(save_dir)
    os.makedirs(save_dir, exist_ok=True)

    bgfiles = os.listdir(args.bg_img_dir)
    bgfiles = [os.path.join(args.bg_img_dir, f) for f in bgfiles]
    bgfiles = [f for f in bgfiles if opath.isfile(f)]

    model = get_model(args)

    src_dir = args.img_dir
    label_dir = args.label_dir if args.label_dir is not None else args.img_dir
    img_files = [f for f in os.listdir(src_dir) if not f.endswith('.txt')]
    for f in tqdm(img_files[6:7], desc='Gen new images', ncols=80):
        fpath = os.path.join(src_dir, f)
        if not opath.isfile(fpath):
            continue
        fbasename_noext = os.path.splitext(f)[0]
        
        img = cv2.imread(fpath, cv2.IMREAD_COLOR)
        mask = model.predict_img(img)

        label_fpath = os.path.join(label_dir, fbasename_noext + '.txt')
        bboxes = read_labels(label_fpath)
        for k in range(5):
            for i, im_bg_f in enumerate(bgfiles[2:3]):
                # fbasename_noext2 = os.path.splitext(opath.basename(im_bg_f))[0]
                bg_img = cv2.imread(im_bg_f, cv2.IMREAD_COLOR)
                merge_img, bboxes2 = hseg.merge_img_with_box(img, mask, bboxes, bg_img)

                fo = opath.join(save_dir, fbasename_noext + f'_{i}_{k}.jpg')
                fo_box = opath.join(save_dir, fbasename_noext + f'_{i}_{k}.txt')
                cv2.imwrite(fo, merge_img)
                save_labels(fo_box, bboxes2)
                # E:\Dev\dataset\hand_detect\hand_wave\baidu_img